name: story-pr

on:
  workflow_dispatch:
    inputs:
      story_filename:
        description: 'Relative path for the story markdown file'
        required: true
      story_content_base64:
        description: 'Base64 encoded story content'
        required: true
      story_summary:
        description: 'Short summary for the PR title'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare metadata
        run: echo "branch=bot/story-${GITHUB_RUN_ID}" >> "$GITHUB_ENV"

      - name: Write story file
        env:
          STORY_FILE: ${{ inputs.story_filename }}
          STORY_CONTENT_B64: ${{ inputs.story_content_base64 }}
        run: |
          python - <<'PY'
          import os
          import base64

          story_path = os.environ['STORY_FILE']
          story_dir = os.path.dirname(story_path)
          if story_dir:
              os.makedirs(story_dir, exist_ok=True)

          content_b64 = os.environ['STORY_CONTENT_B64']
          content_bytes = base64.b64decode(content_b64)

          with open(story_path, 'wb') as f:
              f.write(content_bytes)
          PY

      - name: Configure git user
        run: |
          git config user.name "po-bot"
          git config user.email "po-bot@users.noreply.github.com"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.branch }}
          base: main
          commit-message: 'Add story: ${{ inputs.story_summary }}'
          title: 'Add story: ${{ inputs.story_summary }}'
          body: |
            🤖 Story generated by PO bot.
            - Workflow run: ${{ github.run_id }}
          add-paths: |
            ${{ inputs.story_filename }}
